### ISSUE TITLE
Full compliance with OAF

### ISSUE THREAD

**Issue by quetcodesfire** [stac-utils/stac-api#9]
Check and implement any missing functionality to be fully compliant with the OGC API - Features 1.0 specification.

**Comment by quetcodesfire** [comment]
Looking through the app I think we're good to go here.

http://docs.opengeospatial.org/DRAFTS/17-069r1.html#rfc2616
![image](https://user-images.githubusercontent.com/20568762/70653511-a0c5ba00-1c22-11ea-8108-8ea8ea81336a.png)

**Comment by PeteShepley** [comment]
Are all of the responses compliant as well?
